# Generated by Django 3.0.3 on 2020-03-31 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='first_choice',
            new_name='choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='second_choice',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='third_choice',
        ),
    ]
